-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.rol
(
    id integer NOT NULL DEFAULT nextval('rol_id_seq'::regclass),
    name character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT rol_pk PRIMARY KEY (id),
    CONSTRAINT rol_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.rol_usuario
(
    id bigint NOT NULL DEFAULT nextval('rol_usuario_id_seq'::regclass),
    rol_id integer DEFAULT nextval('rol_usuario_fk_rol_id_seq'::regclass),
    usuario_id bigint NOT NULL DEFAULT nextval('rol_usuario_fk_usuario_id_seq'::regclass),
    CONSTRAINT rol_usuario_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL DEFAULT nextval('usuario_id_seq'::regclass),
    nickname character varying(25) COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pk PRIMARY KEY (id),
    CONSTRAINT usuario_unique UNIQUE (nickname)
);

ALTER TABLE IF EXISTS public.rol_usuario
    ADD CONSTRAINT fk_rol_id FOREIGN KEY (rol_id)
    REFERENCES public.rol (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.rol_usuario
    ADD CONSTRAINT fk_usuario_id FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;

INSERT INTO public.rol ("name") VALUES
	 ('SUPPORT'),
	 ('USER'),
	 ('ADMIN');

INSERT INTO public.usuario (nickname,"password") VALUES
	 ('User','$2b$12$zZi5aNvNjdZn/wwvPgqXwOMwrYGTsQ9IrybmCUd6L5UpIsS0yNDdW'),
	 ('Admin','$2b$12$zZi5aNvNjdZn/wwvPgqXwOMwrYGTsQ9IrybmCUd6L5UpIsS0yNDdW'),
	 ('Support','$2b$12$zZi5aNvNjdZn/wwvPgqXwOMwrYGTsQ9IrybmCUd6L5UpIsS0yNDdW'),
	 ('SupportUser','$2b$12$zZi5aNvNjdZn/wwvPgqXwOMwrYGTsQ9IrybmCUd6L5UpIsS0yNDdW');

INSERT INTO public.rol_usuario () VALUES
	 (2,9),
	 (1,13),
	 (3,13),
	 (2,13),
	 (1,14),
	 (2,14),
	 (1,16),
	 (2,16);
