volumes:
  db_data: {}

services:
  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-auth_jwt}
      PGDATA: /data/postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  api:
    build: .
    image: fastapi-backend
    ports:
      - 8000:8000
    environment:
      DB_URL: postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres-db:5432/${POSTGRES_DB:-auth_jwt}
      ALGORITHM: ${ALGORITHM}
      JWT_SECRET: ${JWT_SECRET}
      ENVIRONMENT: ${ENVIRONMENT}
    links:
      - postgres-db
    env_file:
      - .env
    depends_on:
      - postgres-db
    restart: unless-stopped
